---
title: "Study 1"
author: "Authors"
date: "2022-10-18"
output: html_document
---

#Installing packages
```{r}
install.packages("tidyverse")
install.packages("ggstatsplot")
install.packages("RColorBrewer")
install.packages("haven")
```

#Loading packages
```{r}
library(tidyverse)
library(ggstatsplot)
library(RColorBrewer)
library(haven)
```

#Loading the data file
```{r}
d <- read_sav("/Users/toroklilla/Dropbox/Mac/Desktop/Study_1.sav")
```

#Preparing and checking variables before analyses
```{r}
d$Condition <- as.factor(d$Condition)
d$Condition <-
  recode_factor(d$Condition, `1` = "Fixed Mindset", `2` = "Growth Mindset")
table(d$Condition)

d$Explanation <- as.factor(d$Explanation)
d$Explanation <-
  recode_factor(
    d$Explanation,
    `1` = "Challenge",
    `2` = "Curiosity",
    `3` = "Real Result",
    `4` = "Motivation",
    `5` = "Effect",
    `6` = "Irrelevant/Unknown",
    `7` = "Explicit Self-Protection"
  )
table(d$Explanation)

d$SH_Catt <- as_factor(d$SH_Catt)
d$SH_Catt <- recode_factor(
  d$SH_Catt,
  `0` = "Selected
Debilitating Music",
`1` = "Selected
Neutral Music",
`2` = "Selected
Facilitating Music"
)
table(d$SH_Catt)

d$Challenge_expl <- as.factor(d$Challenge_expl)
d$Challenge_expl <-
  recode_factor(d$Challenge_expl, `0` = "Not Explaining with Challenge Seeking", `1` = "Explaining with Challenge Seeking")
table(d$Challenge_expl)

d$Chall <- as.numeric(d$Chall)

d$SH_cat <- as.factor(d$SH_cat)
d$SH_cat <-
  recode_factor(d$SH_cat, `0` = "Did not Self-Handicap", `1` = "Self-Handicapped")
table(d$SH_cat)
```

#Data analysing and visualizing
```{r}
ggbarstats(
  data = d,
  x = Explanation,
  y = SH_Catt,
  legend.title = "Explanation Types",
  xlab = "Music Selection Category",
  package = "RColorBrewer",
  palette = "Greys"
)
```

#The effect of pre-experimental self-reported challenge seeking on the explaination of challenge seeking
```{r}
mod <-
  glm(
    Challenge_expl ~ Chall,
    family = "binomial",
    data = d,
    subset = SH_cat == "Self-Handicapped"
  )
summary(mod)
tab_model(mod, show.stat = T, use.viewer = T)
```